---
- name: Déplacer la clé privée dans /etc/ssl/private
  copy:
    src: "{{ output_dir }}/private.key"
    dest: "/etc/ssl/private/private.key"
    owner: root
    group: root
    mode: "0600"

- name: Déplacer le certificat dans /etc/ssl/certs
  copy:
    src: "{{ output_dir }}/certificate.crt"
    dest: "/etc/ssl/certs/certificate.crt"
    owner: root
    group: root
    mode: "0600"

- name: Déplacer la clé privée Dovecot dans /etc/ssl/private
  copy:
    src: "{{ output_dir }}/dovecot.key"
    dest: "/etc/ssl/private/dovecot.key"
    owner: root
    group: root
    mode: "0600"

- name: Déplacer le certificat Dovecot dans /etc/ssl/certs
  copy:
    src: "{{ output_dir }}/dovecot.pem"
    dest: "/etc/ssl/certs/dovecot.pem"
    owner: root
    group: root
    mode: "0600"